"use client";

/**
 * Usage examples for <HandwritingSvg />. Not routed and not imported by the app.
 *
 * Every path here comes from `lib/handwriting-paths.ts`, which is generated by
 * `node scripts/gen-handwriting-path.mjs`. Nothing in this file causes a font request or
 * loads opentype.js — that is the whole point of the rework.
 */

import * as React from "react";
import { HandwritingSvg } from "@/components/ui/handwriting-svg";
import { HANDWRITING_PATHS } from "@/lib/handwriting-paths";

/** The product wordmark, drawn once on a splash or auth screen. */
export function WordmarkDemo() {
  return <HandwritingSvg name="nivora" className="h-20 w-auto text-navy" duration={2.4} />;
}

/**
 * A greeting above a login card. The word is repeated by the heading underneath, so the
 * mark is marked decorative rather than announced twice.
 */
export function GreetingDemo() {
  return (
    <div className="flex flex-col items-center gap-2 p-8">
      <HandwritingSvg name="welcome" label={null} className="h-14 w-auto text-teal" delay={0.2} />
      <h1 className="text-title text-navy">Welcome back</h1>
    </div>
  );
}

/** Outline only — no ink flood — and a replay button. */
export function ReplayDemo() {
  const [run, setRun] = React.useState(0);
  return (
    <div className="flex flex-col items-start gap-4 p-8">
      <HandwritingSvg
        name="nivora"
        fill={false}
        strokeWidth={2}
        replayKey={run}
        className="h-24 w-auto text-navy-soft"
      />
      <button type="button" className="text-sm font-medium text-navy underline" onClick={() => setRun((n) => n + 1)}>
        Draw again
      </button>
    </div>
  );
}

/** Finished immediately — for anywhere the mark must be visible before hydration. */
export function StaticDemo() {
  return <HandwritingSvg name="nivora" animate={false} className="h-10 w-auto" />;
}

/** Raw path data, for an outline generated outside the committed set. */
export function RawPathDemo() {
  const entry = HANDWRITING_PATHS.welcome;
  return <HandwritingSvg d={entry.d} viewBox={entry.viewBox} label={entry.text} className="h-12 w-auto" />;
}
